# name you can give any name
name: Continuous Integration and Continuous Deployment on Heroku

# triggers ci cd when you push code to any branch
on:
  push:
  pull_request:
  # this is for manual trigger of ci cd workflow from github actions
  workflow_dispatch:

# jobs is the place where you define all the steps
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Fetch all history for all branches and tags
          fetch-depth: 0

      # install nodejs
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      # install dependencies
      - name: Install Dependencies
        run: npm install

      # run linters
      - name: Run Linters
        run: npm run lint

      # run formater
      - name: Run Formater
        run: npm run format

      # verify the commit message with commitlint and commitlint.config.js
      - name: Verify Commit Message
        uses: wagoid/commitlint-github-action@v3
        with:
          configFile: commitlint.config.cjs

      # build docker image for ci cd pipeline
      - name: Build Docker Image
        run: docker build -t nextjs-cicd-docker .