name: Continuous Integration and Continuous Deployment on Heroku
on:
  push:
    branches:
      - samyak/docker_cicd_integration
      - "**"
  pull_request: null
  workflow_dispatch: null

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Install Dependencies
        run: npm install -f
      - name: Build Docker Image
        run: docker build -t nextjs-cicd-docker .

  deploy:
    name: Deploy to Heroku
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Install Node.js for Heroku CLI
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      # Install Dependencies
      - name: Install Dependencies
        run: npm install -f

      # Build Docker Image
      - name: Build Docker Image
        run: docker-compose up --build -d

      # Login to Heroku Container Registry
      - name: Login to the Heroku Container Registry
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      # Tag and Push Docker Image to Heroku
      - name: Tag and Push Docker Image to Heroku
        run: |
          docker tag nextjs-cicd-docker:1.0 registry.heroku.com/nextjs-cicd-docker/web
          docker push registry.heroku.com/nextjs-cicd-docker/web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      # Release Docker Image to Heroku
      - name: Release Docker Image to Heroku
        run: heroku container:release web -a nextjs-cicd-docker
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
