name: Continuous Integration and Continuous Deployment on Heroku
on:
  push:
    branches:
      - samyak/docker_cicd_integration
      - "**"
  pull_request: null
  workflow_dispatch: null
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Install Dependencies
        run: cd project310_todo && npm install -f
      - name: Build Docker Image
        run: docker build -t nextjs-cicd-docker .
